AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 
    
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: CreatingS3 bucket from CloudFormation
    Properties:
      BucketName: pocpipeline
